### GET all recipes
http://localhost:3000/recipes

### GET recipe by id
http://localhost:3000/recipes/6287e9f9653775daa265d2ec

### POST new recipe
POST http://localhost:3000/recipes HTTP/1.1 Content-Type: application/json


### GET all recipes heroku
https://recipe-book-00.herokuapp.com/recipes

### GET recipe by id heroku
https://recipe-book-00.herokuapp.com/recipes/629136780a023f0b2e88cea2

### POST new recipe heroku
POST https://recipe-book-00.herokuapp.com/ HTTP/1.1 Content-Type: application/json

{
    "name": "Grilled Cheese",
    "ingredients": [
        {
            "quantity": "2",
            "name": "slices of bread"
        }
    ],
    "steps": [
        "Grill the cheese"
    ]
}